version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "autoupdate"
    open-pull-requests-limit: 100

  - package-ecosystem: "nuget"
    directory: "/WikiPageStatsGenerator.Test"
    schedule:
      interval: "daily"
      time: "04:00"
    labels:
      - "autoupdate"
    open-pull-requests-limit: 100
    
  - package-ecosystem: "nuget"
    directory: "/WikiPageStatsGenerator"
    schedule:
      interval: "daily"
      time: "04:20"
    labels:
      - "autoupdate"
    open-pull-requests-limit: 100

  - package-ecosystem: "docker"
    directory: "/WikiPageStatsGenerator.Test"
    schedule:
      interval: "daily"
      time: "04:00"
    labels:
      - "autoupdate"
    open-pull-requests-limit: 100
    
  - package-ecosystem: "docker"
    directory: "/WikiPageStatsGenerator"
    schedule:
      interval: "daily"
      time: "04:20"
    labels:
      - "autoupdate"
    open-pull-requests-limit: 100